# Generated by Django 3.1 on 2020-08-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200531_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-likes']},
        ),
    ]
