# Generated by Django 3.1 on 2020-08-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200808_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['likes']},
        ),
    ]
